version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${PORT:-5001}:5001"
    volumes:
      - app-data:/app/data
      - app-logs:/app/logs
    environment:
      FLASK_ENV: production
      PYTHONUNBUFFERED: 1
      # All other environment variables will be injected by Coolify
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/status"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s

volumes:
  app-data:
    driver: local
  app-logs:
    driver: local