version: '3.8'

services:
  app:
    build: .
    container_name: ai-blog-writer
    restart: unless-stopped
    ports:
      - "${PORT:-5001}:5001"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
    environment:
      - FLASK_ENV=${FLASK_ENV:-production}
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    networks:
      - blog-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/status"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

networks:
  blog-network:
    driver: bridge

volumes:
  data:
    driver: local
  logs:
    driver: local