version: '3.8'

services:
  app:
    image: ${DOCKER_IMAGE:-medium-blog-wordpress-app:latest}
    container_name: ai-blog-writer
    restart: unless-stopped
    ports:
      - "${PORT:-5001}:5001"
    volumes:
      - app-data:/app/data
      - app-logs:/app/logs
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      # All other env vars will be injected by Coolify
    networks:
      - blog-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/status"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

networks:
  blog-network:
    driver: bridge

volumes:
  app-data:
    driver: local
  app-logs:
    driver: local